# Author: Daniel Benjamin Perez Morales
# GitHub: https://github.com/D4nitrix13
# GitLab: https://gitlab.com/D4nitrix13
# Email: danielperezdev@proton.me

[settings -> Malo]
theme = Mal formateado
version = 1.0 Numero Flotante